#-*- coding: utf-8 -*-

TextWidget:

<TextWidget>:
	BoxLayout:
		BoxLayout:
			orientation: 'vertical'
		
			BoxLayout:
				Label:
					text: "Menu Space"
			
			BoxLayout:
				Label:
					text: "Make Semantic Space"
		
			BoxLayout:
				Label:
					text: "Conect Data Base"
		
			BoxLayout:
				Label:
					text: "Input Main Data"
			
		BoxLayout:
			orientation: 'vertical'
			BoxLayout:
				Label:
					text: "Main Space"
		BoxLayout:
			orientation: 'vertical'
			BoxLayout:
				Label:
					text: "Preview Space"
	
	